  // Copyright 2022 Elanskiy Alexandr

#ifndef MODULES_ELANSKI_ALEXANDR_EULER_FUNCTIONS_INCLUDE_FUNCTIONS_INCLUDE_H_
#define MODULES_ELANSKI_ALEXANDR_EULER_FUNCTIONS_INCLUDE_FUNCTIONS_INCLUDE_H_

#include <iostream>

class Euler {
 public:
    int Function_Euler(int number);
};

#endif  // MODULES_ELANSKI_ALEXANDR_EULER_FUNCTIONS_INCLUDE_FUNCTIONS_INCLUDE_H_
