  // Copyright 2022 Elanskiy Alexandr

#ifndef MODULES_ELANSKIY_ALEXANDR_EULER_FUNCTIONS_INCLUDE_FUNCTIONS_INCLUDE_H
#define MODULES_ELANSKIY_ALEXANDR_EULER_FUNCTIONS_INCLUDE_FUNCTIONS_INCLUDE_H

#include <iostream>

class Euler {
public:
    int Function_Euler(int number);
};

#endif  // MODULES_ELANSKIY_ALEXANDR_EULER_FUNCTIONS_INCLUDE_FUNCTIONS_INCLUDE_H
